#!/bin/sh

cd "$(dirname "$0")/.."

deploy_preprod() {
	rsync -avzoK --delete -e ssh * webgist@deblan.fr:/services/web/www/gist.deblan.org/
}


deploy_preprod_lan() {
	rsync -avzoK --delete -e ssh * webgist@hinata:/services/web/www/gist.deblan.org/
}

([ -n "$1" ] && deploy_$1) || deploy_preprod
